### Eventos
GET http://localhost:3000/eventos

### CREATE 
POST http://localhost:3000/eventos
Content-Type: application/json

{
    "tipo": 2,
    "nomeEvento": "Teste create",
    "nomeLocal": "CRIANDO",
    "endereco": "Rua Cria 3",
    "bairro": "Savassi",
    "cidade": "BH",
    "estado": "MG",
    "dataInicioEvento": "15/11/22",
    "horaInicioEvento": "22: 00",
    "valorEntrada": 111
}

### UPDATE
PUT http://localhost:3000/eventos/3
content-type: application/json

{ 
    "tipo": 3,
    "nomeEvento": "Renovar",
    "nomeLocal": "Renova Bar",
    "endereco": "Rua Renova 3",
    "bairro": "Pindorama",
    "cidade": "BH",
    "estado": "MG",
    "dataInicioEvento": "13/11/23",
    "horaInicioEvento": "21: 00",
    "valorEntrada": 5 
}

### GET EVENTO
GET http://localhost:3000/eventos/4

### DELETE EVENTO
DELETE http://localhost:3000/eventos/1

